### ISSUE TITLE
random tiles added even when no updates

### ISSUE THREAD

**Issue by abhikjain360** [WanderHuang/game-2048-tui#1]
When it is not possible for some tiles to combine or move, even then a random tile is added. I think original 2048 ignored such inputs.

example:
initially the grid is
```
0 0 0 0
0 0 0 0
2 0 0 0
4 2 0 0
```
then if user gives down input, there is no possible combination or movement possible, still a random tile is added when instead the move should be ignored.

A simple fix is to check if the `res` is same as the original grid [here](https://github.com/WanderHuang/game-2048-tui/blob/main/src/game.rs#L190-L287), that is, no updates have happened, and then return a `bool` from the function which is checked by [this](https://github.com/WanderHuang/game-2048-tui/blob/main/src/game.rs#L38) before doing a random insert.

**Comment by WanderHuang** [comment]
@abhikjain360 Yes, this is a bug. I will fix it later.
